### ISSUE TITLE
Blocker

### ISSUE THREAD

**Issue by verdanzo** [maroulacanilao/CAPSTN3_HDRP#12]
Falling in one of the randomized levels dan created gets you stuck in darkness and reduce player's health to 0, player does not die thus wont return to house and start next day.

esc key seize to function but tab key to access menu works. Can leave blocker by using leave dungeon

 Player's health remains at 0 unless player heals or rest for the next day.

**Comment by iambaltz** [comment]
Fixed this by adding reference to teleport transform in Level 9.

**Comment by iambaltz** [comment]
I fixed the dungeonscene checking because it's not activating the death canvas to proceed to the next day.
